module(name = "bazel-trace-grpc")

bazel_dep(name = "rules_python", version = "2.3.2")
bazel_dep(name = "protobuf", version = "36.1.bcr.1")
bazel_dep(name = "googleapis", version = "0.0.0-20260825-d10ac924")
bazel_dep(name = "bazel_remote_apis")

# TODO: https://github.com/bazelbuild/remote-apis/issues/373
git_override(
    module_name = "bazel_remote_apis",
    remote = "https://github.com/bazelbuild/remote-apis.git",
    commit = "9e084d0e43e717128ee72b5be584a7ba33e8006b", # v2.12.0
)

use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")(
    name = "remote_execution_log_proto",
    url = "https://raw.githubusercontent.com/bazelbuild/bazel/37413dc64e3a38db235c1547f10bd50e215b14a2/src/main/protobuf/remote_execution_log.proto",
    integrity = "sha256-f9awJ9DMxb892tG9V266bzm5cMPqLydIJyU/ypDQjxc=",
    downloaded_file_path = "remote_execution_log.proto",
)

#-------------------------------------------------------------------------------

bazel_dep(name = "llvm", version = "0.8.19", dev_dependency = True)
register_toolchains("@llvm//toolchain:all", dev_dependency = True)

use_extension(
    "@rules_python//python/extensions:python.bzl", "python",
    dev_dependency = True
).defaults(python_version = "3.14")
